// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX_aMoTgBMjVmn4szP4JdpSCKTgqXb6Xs',
    appId: '1:455268554992:web:e012e40098960fd4a8ca35',
    messagingSenderId: '455268554992',
    projectId: 'food-delivery-36ed4',
    authDomain: 'food-delivery-36ed4.firebaseapp.com',
    storageBucket: 'food-delivery-36ed4.appspot.com',
    measurementId: 'G-41JL9ZC006',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArff6r96lPGvqXz5QmjRM-XYEKrFEC3Xs',
    appId: '1:455268554992:android:939ab5e8063d0228a8ca35',
    messagingSenderId: '455268554992',
    projectId: 'food-delivery-36ed4',
    storageBucket: 'food-delivery-36ed4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3FbDjLTvYuP2mH5uLqCxdVdI5_F2dXQA',
    appId: '1:455268554992:ios:59b9708720f8e282a8ca35',
    messagingSenderId: '455268554992',
    projectId: 'food-delivery-36ed4',
    storageBucket: 'food-delivery-36ed4.appspot.com',
    iosClientId: '455268554992-40k2bcu7g83qgeppoq6lko82epad848f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3FbDjLTvYuP2mH5uLqCxdVdI5_F2dXQA',
    appId: '1:455268554992:ios:59b9708720f8e282a8ca35',
    messagingSenderId: '455268554992',
    projectId: 'food-delivery-36ed4',
    storageBucket: 'food-delivery-36ed4.appspot.com',
    iosClientId: '455268554992-40k2bcu7g83qgeppoq6lko82epad848f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddelivery',
  );
}
